package cl.minsal.semantikos.loaders;

import cl.minsal.semantikos.clients.ServiceLocator;
import cl.minsal.semantikos.kernel.components.*;
import cl.minsal.semantikos.model.ConceptSMTK;
import cl.minsal.semantikos.model.LoadException;
import cl.minsal.semantikos.model.LoadLog;
import cl.minsal.semantikos.model.SMTKLoader;
import cl.minsal.semantikos.model.basictypes.BasicTypeValue;
import cl.minsal.semantikos.model.categories.Category;
import cl.minsal.semantikos.model.categories.CategoryFactory;
import cl.minsal.semantikos.model.descriptions.Description;
import cl.minsal.semantikos.model.descriptions.DescriptionType;
import cl.minsal.semantikos.model.helpertables.HelperTable;
import cl.minsal.semantikos.model.helpertables.HelperTableRow;
import cl.minsal.semantikos.model.relationships.*;
import cl.minsal.semantikos.model.snomedct.ConceptSCT;
import cl.minsal.semantikos.model.tags.TagSMTK;
import cl.minsal.semantikos.model.tags.TagSMTKFactory;
import cl.minsal.semantikos.model.users.User;
import cl.minsal.semantikos.util.StringUtils;

import java.sql.Timestamp;
import java.util.*;

import static cl.minsal.semantikos.model.LoadLog.ERROR;
import static cl.minsal.semantikos.model.LoadLog.INFO;
import static cl.minsal.semantikos.model.relationships.SnomedCTRelationship.ES_UN;
import static java.util.Collections.EMPTY_LIST;

/**
 * Created by root on 15-06-17.
 */
public class MCCEConceptLoader extends EntityLoader {

    ConceptManager conceptManager = (ConceptManager) ServiceLocator.getInstance().getService(ConceptManager.class);
    DescriptionManager descriptionManager = (DescriptionManager) ServiceLocator.getInstance().getService(DescriptionManager.class);
    TagManager tagManager = (TagManager) ServiceLocator.getInstance().getService(TagManager.class);
    SnomedCTManager snomedCTManager = (SnomedCTManager) ServiceLocator.getInstance().getService(SnomedCTManager.class);
    HelperTablesManager helperTableManager = (HelperTablesManager) ServiceLocator.getInstance().getService(HelperTablesManager.class);

    public static final Map<String, Integer> mcceConceptFields;
    static
    {
        mcceConceptFields = new HashMap<String, Integer>();
        mcceConceptFields.put("CONCEPTO_ID", 0);
        mcceConceptFields.put("DESCRIPCION", 1);
        mcceConceptFields.put("DESC_ABREVIADA", 2);
        mcceConceptFields.put("ESTADO", 3);
        mcceConceptFields.put("SENSIBLE_MAYUSCULA", 4);
        mcceConceptFields.put("CREAC_NOMBRE", 5);
        mcceConceptFields.put("REVISADO", 6);
        mcceConceptFields.put("CONSULTAR", 7);
        mcceConceptFields.put("SCT_ID", 8);
        mcceConceptFields.put("SCT_TERMINO", 9);
        mcceConceptFields.put("SINONIMO", 10);
        mcceConceptFields.put("GRUPOS_JERARQUICOS", 11);
        mcceConceptFields.put("MEDICAMENTO_CLINICO_FK", 12);
        mcceConceptFields.put("MEDICAMENTO_CLINICO_DESC", 13);
        mcceConceptFields.put("TIPO_FK", 14);
        mcceConceptFields.put("TIPO_DESC", 15);
        mcceConceptFields.put("CANTIDAD", 16);
        mcceConceptFields.put("UNIDAD_MEDIDA_CANTIDAD_FK", 17);
        mcceConceptFields.put("UNIDAD_MEDIDA_CANTIDAD_DESC", 18);
        mcceConceptFields.put("PACK_MULTI_CANTIDAD", 19);
        mcceConceptFields.put("PACK_MULTI_UNIDAD_FK", 20);
        mcceConceptFields.put("PACK_MULTI_UNIDAD_DESC", 21);
        mcceConceptFields.put("VOLUMEN_TOTAL_CANTIDAD", 22);
        mcceConceptFields.put("VOLUMEN_TOTAL_UNIDAD_FK", 23);
        mcceConceptFields.put("VOLUMEN_TOTAL_UNIDAD_DESC", 24);
    }

    Map<Long, ConceptSMTK> conceptSMTKMap = new HashMap<>();

    Map<String, Description> descriptionMap = new HashMap<>();

    public void loadConceptFromFileLine(String line, User user) throws LoadException {

        String[] tokens = line.split(separator,-1);
        long id = Long.parseLong(tokens[mcceConceptFields.get("CONCEPTO_ID")]);

        try {

            /*Recuperando datos Concepto*/

            /*Se recuperan los datos relevantes. El resto serán calculados por el componente de negocio*/
            boolean toBeReviewed = tokens[mcceConceptFields.get("REVISADO")].equals("Si");
            boolean toBeConsulted = tokens[mcceConceptFields.get("CONSULTAR")].equals("Si");
            boolean autogenerated = tokens[mcceConceptFields.get("CREAC_NOMBRE")].equals("Autogenerado");

            Category category = CategoryFactory.getInstance().findCategoryByName("Fármacos - Medicamento Clínico con Envase");
            TagSMTK tagSMTK = TagSMTKFactory.getInstance().findTagSMTKByName("producto");

            ConceptSMTK conceptSMTK = new ConceptSMTK(category);
            conceptSMTK.setToBeConsulted(toBeConsulted);
            conceptSMTK.setToBeReviewed(toBeReviewed);
            conceptSMTK.setCategory(category);
            conceptSMTK.setTagSMTK(tagSMTK);

            /*Recuperando datos Descripciones*/

            /*Recuperando descripcion preferida*/
            String term = StringUtils.normalizeSpaces(tokens[mcceConceptFields.get("DESCRIPCION")]).trim();
            boolean caseSensitive = tokens[mcceConceptFields.get("SENSIBLE_MAYUSCULA")].equals("Sensible");
            DescriptionType descriptionType = DescriptionType.PREFERIDA;

            Description descriptionFavourite = new Description(conceptSMTK, term, descriptionType);
            descriptionFavourite.setCaseSensitive(caseSensitive);
            descriptionFavourite.setCreatorUser(user);
            descriptionFavourite.setAutogeneratedName(autogenerated);

            if(descriptionMap.containsKey(descriptionFavourite.getTerm())) {
                SMTKLoader.logWarning(new LoadLog("Término repetido para descripción "+descriptionFavourite.toString()+". Se descarta descripción", INFO));
            }
            else {
                descriptionMap.put(descriptionFavourite.getTerm(), descriptionFavourite);
                conceptSMTK.addDescription(descriptionFavourite);
            }

            /*Recuperando descripcion FSN*/
            term = descriptionFavourite.getTerm()+" ("+tagSMTK.getName()+")";
            descriptionType = DescriptionType.FSN;

            Description descriptionFSN = new Description(conceptSMTK, term, descriptionType);
            descriptionFSN.setCaseSensitive(caseSensitive);
            descriptionFSN.setCreatorUser(user);
            descriptionFSN.setAutogeneratedName(autogenerated);

            if(descriptionMap.containsKey(descriptionFSN.getTerm())) {
                SMTKLoader.logWarning(new LoadLog("Término repetido para descripción "+descriptionFSN.toString()+". Se descarta descripción", INFO));
            }
            else {
                descriptionMap.put(descriptionFSN.getTerm(), descriptionFSN);
                conceptSMTK.addDescription(descriptionFSN);
            }

            /*Recuperando descripcion Abreviada*/
            term = StringUtils.normalizeSpaces(tokens[mcceConceptFields.get("DESC_ABREVIADA")]).trim();

            if(!StringUtils.isEmpty(term)) {
                descriptionType = DescriptionType.ABREVIADA;

                Description descriptionAbbreviated = new Description(conceptSMTK, term, descriptionType);
                descriptionAbbreviated.setCaseSensitive(caseSensitive);
                descriptionAbbreviated.setCreatorUser(user);
                descriptionAbbreviated.setAutogeneratedName(autogenerated);

                if(descriptionMap.containsKey(descriptionAbbreviated.getTerm())) {
                    SMTKLoader.logWarning(new LoadLog("Término repetido para descripción "+descriptionAbbreviated.toString()+". Se descarta descripción", INFO));
                }
                else {
                    descriptionMap.put(descriptionAbbreviated.getTerm(), descriptionAbbreviated);
                    conceptSMTK.addDescription(descriptionAbbreviated);
                }
            }

            /*Recuperando Sinónimos*/
            String synonyms = tokens[mcceConceptFields.get("SINONIMO")];
            descriptionType = DescriptionType.SYNONYMOUS;

            String[] synonymsTokens = synonyms.split("•");

            for (String synonymsToken : synonymsTokens) {

                if(synonymsToken.isEmpty() || synonymsToken.equals("\"")) {
                    continue;
                }

                term = StringUtils.normalizeSpaces(synonymsToken.split("-")[1]).trim();

                Description description = new Description(conceptSMTK, term, descriptionType);
                description.setCaseSensitive(caseSensitive);
                description.setCreatorUser(user);
                description.setAutogeneratedName(autogenerated);

                if(descriptionMap.containsKey(description.getTerm())) {
                    SMTKLoader.logWarning(new LoadLog("Término repetido para descripción "+description.toString()+". Se descarta descripción", INFO));
                }
                else {
                    descriptionMap.put(description.getTerm(), description);
                    conceptSMTK.addDescription(description);
                }
            }

            descriptionMap.clear();

            /*Recuperando datos Relaciones*/
            String idConceptSCTName = tokens[mcceConceptFields.get("SCT_ID")];

            /*Por defecto se mapea a un concepto SNOMED Genérico*/
            long idConceptSCT = 373873005;

            if(!idConceptSCTName.isEmpty()) {
                idConceptSCT = Long.parseLong(tokens[mcceConceptFields.get("SCT_ID")]);
            }

            String relationshipType = ES_UN;

            ConceptSCT conceptSCT = snomedCTManager.getConceptByID(idConceptSCT);

            if(conceptSCT == null) {
                throw new LoadException(path.toString(), id, "Relación referencia a concepto SCT inexistente", ERROR);
            }

            /**Se obtiene la definición de relacion SNOMED CT**/
            RelationshipDefinition relationshipDefinition = conceptSMTK.getCategory().findRelationshipDefinitionsByName(TargetDefinition.SNOMED_CT).get(0);

            RelationshipAttributeDefinition attDef;

            RelationshipAttribute ra;

            Relationship relationshipSnomed = new Relationship(conceptSMTK, conceptSCT, relationshipDefinition, new ArrayList<RelationshipAttribute>(), new Timestamp(System.currentTimeMillis()));

            /**Para esta definición, se obtiente el atributo tipo de relación**/
            for (RelationshipAttributeDefinition attDef1 : relationshipDefinition.getRelationshipAttributeDefinitions()) {

                if (attDef1.isRelationshipTypeAttribute()) {
                    HelperTable helperTable = (HelperTable) attDef1.getTargetDefinition();

                    List<HelperTableRow> relationshipTypes = helperTableManager.searchRows(helperTable, relationshipType);

                    if (relationshipTypes.size() == 0) {
                        throw new LoadException(path.toString(), id, "No existe un tipo de relación de nombre: "+relationshipType, ERROR);
                    }

                    ra = new RelationshipAttribute(attDef1, relationshipSnomed, relationshipTypes.get(0));
                    relationshipSnomed.getRelationshipAttributes().add(ra);
                }
            }

            /* Generando Grupo */
            BasicTypeValue group = new BasicTypeValue(0);

            RelationshipAttributeDefinition attDefGroup = relationshipDefinition.findRelationshipAttributeDefinitionsByName("Grupo").get(0);

            RelationshipAttribute raGroup = new RelationshipAttribute(attDefGroup, relationshipSnomed, group);
            relationshipSnomed.getRelationshipAttributes().add(raGroup);

            conceptSMTK.addRelationship(relationshipSnomed);

            HelperTable helperTable;

            /*Generando Comercializado*/
            BasicTypeValue basicTypeValue = new BasicTypeValue(true);

            relationshipDefinition = conceptSMTK.getCategory().findRelationshipDefinitionsByName(TargetDefinition.COMERCIALIZADO).get(0);

            Relationship relationshipMarketed = new Relationship(conceptSMTK, basicTypeValue, relationshipDefinition, new ArrayList<RelationshipAttribute>(), new Timestamp(System.currentTimeMillis()));

            conceptSMTK.addRelationship(relationshipMarketed);

            /*Recuperando Medicamento Clínico*/

            String mcName = tokens[mcceConceptFields.get("MEDICAMENTO_CLINICO_DESC")];

            if(!StringUtils.isEmpty(mcName)) {

                relationshipDefinition = category.findRelationshipDefinitionsByName("Medicamento Clínico").get(0);

                List<Description> mc = descriptionManager.searchDescriptionsPerfectMatch(StringUtils.normalizeSpaces(mcName).trim(), Arrays.asList(new Category[]{CategoryFactory.getInstance().findCategoryByName("Fármacos - Medicamento Clínico")}), null);

                if(mc.isEmpty()) {
                    throw new LoadException(path.toString(), id, "No existe un MC con preferida: "+mcName, ERROR);
                }

                if(!mc.get(0).getConceptSMTK().isModeled()) {
                    throw new LoadException(path.toString(), id, "EL MC: "+mcName+" no está modelado, se descarta este MC", ERROR);
                }

                Relationship relationshipMC = new Relationship(conceptSMTK, mc.get(0).getConceptSMTK(), relationshipDefinition, new ArrayList<RelationshipAttribute>(), new Timestamp(System.currentTimeMillis()));

                conceptSMTK.addRelationship(relationshipMC);
            }

            /*Recuperando Condición de Venta*/

            String mcceTypeName = tokens[mcceConceptFields.get("TIPO_DESC")];

            if(!StringUtils.isEmpty(mcceTypeName)) {

                relationshipDefinition = category.findRelationshipDefinitionsByName("Tipo de MCCE").get(0);

                helperTable = (HelperTable) relationshipDefinition.getTargetDefinition();

                List<HelperTableRow> prescriptionState = helperTableManager.searchRows(helperTable, mcceTypeName);

                if(prescriptionState.isEmpty()) {
                    throw new LoadException(path.toString(), id, "No existe un Tipo de MCCE con glosa: "+mcceTypeName, ERROR);
                }

                Relationship relationshipSaleCondition = new Relationship(conceptSMTK, prescriptionState.get(0), relationshipDefinition, new ArrayList<RelationshipAttribute>(), new Timestamp(System.currentTimeMillis()));

                conceptSMTK.addRelationship(relationshipSaleCondition);
            }

            /*Recuperando Cantidad*/

            String quantityName = tokens[mcceConceptFields.get("CANTIDAD")];

            if(!quantityName.trim().isEmpty()) {

                relationshipDefinition = category.findRelationshipDefinitionsByName("Cantidad").get(0);

                basicTypeValue = new BasicTypeValue(Integer.parseInt(quantityName.trim()));

                Relationship relationshipQuantity = new Relationship(conceptSMTK, basicTypeValue, relationshipDefinition, new ArrayList<RelationshipAttribute>(), new Timestamp(System.currentTimeMillis()));

                //Unidad
                attDef = relationshipDefinition.findRelationshipAttributeDefinitionsByName("Unidad").get(0);

                String quantityUnitName = tokens[mcceConceptFields.get("UNIDAD_MEDIDA_CANTIDAD_DESC")];

                helperTable = (HelperTable) attDef.getTargetDefinition();

                List<HelperTableRow> volumneUnit = helperTableManager.searchRows(helperTable, quantityUnitName);

                ra = new RelationshipAttribute(attDef, relationshipQuantity, volumneUnit.get(0));
                relationshipQuantity.getRelationshipAttributes().add(ra);

                conceptSMTK.addRelationship(relationshipQuantity);
            }

            /*Recuperando Cantidad Pack Multi*/

            String quantityPackMultiName = tokens[mcceConceptFields.get("PACK_MULTI_CANTIDAD")];

            if(!quantityPackMultiName.trim().isEmpty()) {

                relationshipDefinition = category.findRelationshipDefinitionsByName("Cantidad Pack Multi").get(0);

                basicTypeValue = new BasicTypeValue(Integer.parseInt(quantityName.trim()));

                Relationship relationshipQuantityPackMulti = new Relationship(conceptSMTK, basicTypeValue, relationshipDefinition, new ArrayList<RelationshipAttribute>(), new Timestamp(System.currentTimeMillis()));

                //Unidad
                attDef = relationshipDefinition.findRelationshipAttributeDefinitionsByName("Unidad Pack Multi").get(0);

                String quantityPackMultiUnitName = tokens[mcceConceptFields.get("PACK_MULTI_UNIDAD_DESC")];

                helperTable = (HelperTable) attDef.getTargetDefinition();

                List<HelperTableRow> volumneUnit = helperTableManager.searchRows(helperTable, quantityPackMultiUnitName);

                ra = new RelationshipAttribute(attDef, relationshipQuantityPackMulti, volumneUnit.get(0));
                relationshipQuantityPackMulti.getRelationshipAttributes().add(ra);

                conceptSMTK.addRelationship(relationshipQuantityPackMulti);
            }

            /*Recuperando Volumen Total*/

            String volumeName = tokens[mcceConceptFields.get("VOLUMEN_TOTAL_CANTIDAD")];

            if(!StringUtils.isEmpty(volumeName)) {

                relationshipDefinition = category.findRelationshipDefinitionsByName("Cantidad Volumen Total").get(0);

                basicTypeValue = new BasicTypeValue(Float.parseFloat(volumeName.replace(",",".")));

                Relationship relationshipVolume = new Relationship(conceptSMTK, basicTypeValue, relationshipDefinition, new ArrayList<RelationshipAttribute>(), new Timestamp(System.currentTimeMillis()));

                //Unidad Volumen
                attDef = relationshipDefinition.findRelationshipAttributeDefinitionsByName("Unidad Volumen Total").get(0);

                String volumeUnitName = tokens[mcceConceptFields.get("VOLUMEN_TOTAL_UNIDAD_DESC")];

                if(volumeUnitName.isEmpty()) {
                    throw new LoadException(path.toString(), id, "No se ha especificado una unidad para esta cantidad de volumen total: "+volumeName, ERROR);
                }

                helperTable = (HelperTable) attDef.getTargetDefinition();

                List<HelperTableRow> volumneUnit = helperTableManager.searchRows(helperTable, volumeUnitName);

                ra = new RelationshipAttribute(attDef, relationshipVolume, volumneUnit.get(0));
                relationshipVolume.getRelationshipAttributes().add(ra);

                conceptSMTK.addRelationship(relationshipVolume);
            }


            conceptSMTKMap.put(id, conceptSMTK);
        }
        catch (Exception e) {
            throw new LoadException(path.toString(), id, "Error desconocido: "+e.toString(), ERROR);
        }

    }

    public void loadAllConcepts(SMTKLoader smtkLoader) {

        smtkLoader.logInfo(new LoadLog("Comprobando Conceptos Fármacos - Medicamento Clínico con Envase", INFO));

        try {

            initReader(smtkLoader.MCCE_PATH);

            String line;

            while ((line = reader.readLine()) != null) {
                try {
                    loadConceptFromFileLine(line, smtkLoader.getUser());
                    smtkLoader.incrementConceptsProcessed(1);
                }
                catch (LoadException e) {
                    smtkLoader.logError(e);
                    e.printStackTrace();
                }
            }

            haltReader();

            smtkLoader.logTick();

        } catch (Exception e) {
            smtkLoader.logError(new LoadException(path.toString(), null, e.getMessage(), ERROR));
            e.printStackTrace();
        } catch (LoadException e) {
            e.printStackTrace();
        }
    }

    public void persistAllConcepts(SMTKLoader smtkLoader) {

        smtkLoader.logInfo(new LoadLog("Persisitiendo Conceptos Fármacos - Medicamento Clínico con Envase", INFO));

        smtkLoader.setConceptsProcessed(0);

        Iterator it = conceptSMTKMap.entrySet().iterator();

        while (it.hasNext()) {

            Map.Entry pair = (Map.Entry) it.next();

            try {
                conceptManager.persist((ConceptSMTK)pair.getValue(), smtkLoader.getUser());
                smtkLoader.incrementConceptsProcessed(1);
            }
            catch (Exception e) {
                smtkLoader.logError(new LoadException(path.toString(), (Long) pair.getKey(), e.getMessage(), ERROR));
                e.printStackTrace();
            }

            it.remove(); // avoids a ConcurrentModificationException
        }

        smtkLoader.logTick();
    }

    public void processConcepts(SMTKLoader smtkLoader) {
        loadAllConcepts(smtkLoader);
        persistAllConcepts(smtkLoader);
    }

}
