//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.36366.
// 
#pragma warning disable 1591

namespace ConexionServiciosWS.ServicioDeIngresoWS1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36366")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioDeIngresoSoapBinding", Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class ServicioDeIngreso : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback codificacionDeNuevoTerminoOperationCompleted;
        
        private System.Threading.SendOrPostCallback incrementarContadorDescripcionConsumidaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioDeIngreso() {
            this.Url = global::ConexionServiciosWS.Properties.Settings.Default.ConexionServiciosWS_ServicioDeIngresoWS1_ServicioDeIngreso;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event codificacionDeNuevoTerminoCompletedEventHandler codificacionDeNuevoTerminoCompleted;
        
        /// <remarks/>
        public event incrementarContadorDescripcionConsumidaCompletedEventHandler incrementarContadorDescripcionConsumidaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ws.semantikos.minsal.cl/", ResponseNamespace="http://service.ws.semantikos.minsal.cl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("respuestaCodificacionDeNuevoTermino")]
        public RespuestaCodificacionDeNuevoTermino codificacionDeNuevoTermino(PeticionCodificacionDeNuevoTermino peticionCodificacionDeNuevoTermino) {
            object[] results = this.Invoke("codificacionDeNuevoTermino", new object[] {
                        peticionCodificacionDeNuevoTermino});
            return ((RespuestaCodificacionDeNuevoTermino)(results[0]));
        }
        
        /// <remarks/>
        public void codificacionDeNuevoTerminoAsync(PeticionCodificacionDeNuevoTermino peticionCodificacionDeNuevoTermino) {
            this.codificacionDeNuevoTerminoAsync(peticionCodificacionDeNuevoTermino, null);
        }
        
        /// <remarks/>
        public void codificacionDeNuevoTerminoAsync(PeticionCodificacionDeNuevoTermino peticionCodificacionDeNuevoTermino, object userState) {
            if ((this.codificacionDeNuevoTerminoOperationCompleted == null)) {
                this.codificacionDeNuevoTerminoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncodificacionDeNuevoTerminoOperationCompleted);
            }
            this.InvokeAsync("codificacionDeNuevoTermino", new object[] {
                        peticionCodificacionDeNuevoTermino}, this.codificacionDeNuevoTerminoOperationCompleted, userState);
        }
        
        private void OncodificacionDeNuevoTerminoOperationCompleted(object arg) {
            if ((this.codificacionDeNuevoTerminoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.codificacionDeNuevoTerminoCompleted(this, new codificacionDeNuevoTerminoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ws.semantikos.minsal.cl/", ResponseNamespace="http://service.ws.semantikos.minsal.cl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("descripcionCounter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Descripcion incrementarContadorDescripcionConsumida([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string descriptionID) {
            object[] results = this.Invoke("incrementarContadorDescripcionConsumida", new object[] {
                        descriptionID});
            return ((Descripcion)(results[0]));
        }
        
        /// <remarks/>
        public void incrementarContadorDescripcionConsumidaAsync(string descriptionID) {
            this.incrementarContadorDescripcionConsumidaAsync(descriptionID, null);
        }
        
        /// <remarks/>
        public void incrementarContadorDescripcionConsumidaAsync(string descriptionID, object userState) {
            if ((this.incrementarContadorDescripcionConsumidaOperationCompleted == null)) {
                this.incrementarContadorDescripcionConsumidaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnincrementarContadorDescripcionConsumidaOperationCompleted);
            }
            this.InvokeAsync("incrementarContadorDescripcionConsumida", new object[] {
                        descriptionID}, this.incrementarContadorDescripcionConsumidaOperationCompleted, userState);
        }
        
        private void OnincrementarContadorDescripcionConsumidaOperationCompleted(object arg) {
            if ((this.incrementarContadorDescripcionConsumidaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.incrementarContadorDescripcionConsumidaCompleted(this, new incrementarContadorDescripcionConsumidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class PeticionCodificacionDeNuevoTermino {
        
        private string establecimientoField;
        
        private string idConceptoField;
        
        private string terminoField;
        
        private string tipoDescripcionField;
        
        private bool esSensibleAMayusculasField;
        
        private string emailField;
        
        private string observacionField;
        
        private string profesionalField;
        
        private string profesionField;
        
        private string especialidadField;
        
        private string subespecialidadField;
        
        private string categoriaField;
        
        public PeticionCodificacionDeNuevoTermino() {
            this.tipoDescripcionField = "Preferida";
            this.esSensibleAMayusculasField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string establecimiento {
            get {
                return this.establecimientoField;
            }
            set {
                this.establecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idConcepto {
            get {
                return this.idConceptoField;
            }
            set {
                this.idConceptoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string termino {
            get {
                return this.terminoField;
            }
            set {
                this.terminoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DefaultValueAttribute("Preferida")]
        public string tipoDescripcion {
            get {
                return this.tipoDescripcionField;
            }
            set {
                this.tipoDescripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool esSensibleAMayusculas {
            get {
                return this.esSensibleAMayusculasField;
            }
            set {
                this.esSensibleAMayusculasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string profesional {
            get {
                return this.profesionalField;
            }
            set {
                this.profesionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string profesion {
            get {
                return this.profesionField;
            }
            set {
                this.profesionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sub-especialidad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subespecialidad {
            get {
                return this.subespecialidadField;
            }
            set {
                this.subespecialidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class CrossmapSet {
        
        private string abbreviatedNameField;
        
        private string nameField;
        
        private int versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string abbreviatedName {
            get {
                return this.abbreviatedNameField;
            }
            set {
                this.abbreviatedNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class CrossmapSetMember {
        
        private long idCrossmapSetMemberField;
        
        private CrossmapSet crossmapSetField;
        
        private string codeField;
        
        private string glossField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idCrossmapSetMember {
            get {
                return this.idCrossmapSetMemberField;
            }
            set {
                this.idCrossmapSetMemberField = value;
            }
        }
        
        /// <remarks/>
        public CrossmapSet crossmapSet {
            get {
                return this.crossmapSetField;
            }
            set {
                this.crossmapSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gloss {
            get {
                return this.glossField;
            }
            set {
                this.glossField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class IndirectCrossmap {
        
        private int mapGroupField;
        
        private int mapPriorityField;
        
        private string mapRuleField;
        
        private string mapAdviceField;
        
        private string mapTargetField;
        
        private long correlationField;
        
        private long idCrossmapCategoryField;
        
        private bool stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mapGroup {
            get {
                return this.mapGroupField;
            }
            set {
                this.mapGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mapPriority {
            get {
                return this.mapPriorityField;
            }
            set {
                this.mapPriorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mapRule {
            get {
                return this.mapRuleField;
            }
            set {
                this.mapRuleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mapAdvice {
            get {
                return this.mapAdviceField;
            }
            set {
                this.mapAdviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mapTarget {
            get {
                return this.mapTargetField;
            }
            set {
                this.mapTargetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long correlation {
            get {
                return this.correlationField;
            }
            set {
                this.correlationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idCrossmapCategory {
            get {
                return this.idCrossmapCategoryField;
            }
            set {
                this.idCrossmapCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class RelacionSnomedCT {
        
        private string tipoRelacionField;
        
        private string idConceptoSnomedCTField;
        
        private string descripcionField;
        
        private string grupoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoRelacion {
            get {
                return this.tipoRelacionField;
            }
            set {
                this.tipoRelacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idConceptoSnomedCT {
            get {
                return this.idConceptoSnomedCTField;
            }
            set {
                this.idConceptoSnomedCTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string grupo {
            get {
                return this.grupoField;
            }
            set {
                this.grupoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class AtributoRelacion {
        
        private Objetivo objetivoField;
        
        private DefinicionRelacionAtributo definicionAtributoRelacionField;
        
        private Relacion relacionField;
        
        private string tipoField;
        
        private string nombreField;
        
        private string valorField;
        
        /// <remarks/>
        public Objetivo objetivo {
            get {
                return this.objetivoField;
            }
            set {
                this.objetivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DefinicionRelacionAtributo definicionAtributoRelacion {
            get {
                return this.definicionAtributoRelacionField;
            }
            set {
                this.definicionAtributoRelacionField = value;
            }
        }
        
        /// <remarks/>
        public Relacion relacion {
            get {
                return this.relacionField;
            }
            set {
                this.relacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class Objetivo {
        
        private string tipoField;
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private long idModuloField;
        
        private bool idModuloFieldSpecified;
        
        private long estadoDefinicionIdField;
        
        private bool estadoDefinicionIdFieldSpecified;
        
        private bool validoField;
        
        private bool validoFieldSpecified;
        
        private System.DateTime tiempoEfectivoField;
        
        private bool tiempoEfectivoFieldSpecified;
        
        private string valorField;
        
        private Concepto conceptoSMTKField;
        
        private Relacion relacionField;
        
        private TablaAuxiliar tablaAuxiliarField;
        
        private ObjetivoEntry[] fieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idModulo {
            get {
                return this.idModuloField;
            }
            set {
                this.idModuloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idModuloSpecified {
            get {
                return this.idModuloFieldSpecified;
            }
            set {
                this.idModuloFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long estadoDefinicionId {
            get {
                return this.estadoDefinicionIdField;
            }
            set {
                this.estadoDefinicionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoDefinicionIdSpecified {
            get {
                return this.estadoDefinicionIdFieldSpecified;
            }
            set {
                this.estadoDefinicionIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool valido {
            get {
                return this.validoField;
            }
            set {
                this.validoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validoSpecified {
            get {
                return this.validoFieldSpecified;
            }
            set {
                this.validoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime tiempoEfectivo {
            get {
                return this.tiempoEfectivoField;
            }
            set {
                this.tiempoEfectivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tiempoEfectivoSpecified {
            get {
                return this.tiempoEfectivoFieldSpecified;
            }
            set {
                this.tiempoEfectivoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Concepto conceptoSMTK {
            get {
                return this.conceptoSMTKField;
            }
            set {
                this.conceptoSMTKField = value;
            }
        }
        
        /// <remarks/>
        public Relacion relacion {
            get {
                return this.relacionField;
            }
            set {
                this.relacionField = value;
            }
        }
        
        /// <remarks/>
        public TablaAuxiliar tablaAuxiliar {
            get {
                return this.tablaAuxiliarField;
            }
            set {
                this.tablaAuxiliarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ObjetivoEntry[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class Concepto {
        
        private string idField;
        
        private bool aSerRevisadoField;
        
        private bool aSerRevisadoFieldSpecified;
        
        private bool aSerConsultadoField;
        
        private bool aSerConsultadoFieldSpecified;
        
        private bool modeladoField;
        
        private bool modeladoFieldSpecified;
        
        private bool completamenteDefinidoField;
        
        private bool completamenteDefinidoFieldSpecified;
        
        private bool publicadoField;
        
        private bool publicadoFieldSpecified;
        
        private bool validoField;
        
        private bool validoFieldSpecified;
        
        private System.DateTime validoHastaField;
        
        private bool validoHastaFieldSpecified;
        
        private string observacionField;
        
        private Categoria categoriaField;
        
        private RefSet[] refSetsField;
        
        private Descripcion[] descripcionesField;
        
        private Atributo[] atributosField;
        
        private Relacion[] relacionesField;
        
        private RelacionSnomedCT[] relacionesSnomedCTField;
        
        private IndirectCrossmap[] crossmapsIndirectosField;
        
        private CrossmapSetMember[] crossmapsDirectosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool aSerRevisado {
            get {
                return this.aSerRevisadoField;
            }
            set {
                this.aSerRevisadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aSerRevisadoSpecified {
            get {
                return this.aSerRevisadoFieldSpecified;
            }
            set {
                this.aSerRevisadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool aSerConsultado {
            get {
                return this.aSerConsultadoField;
            }
            set {
                this.aSerConsultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aSerConsultadoSpecified {
            get {
                return this.aSerConsultadoFieldSpecified;
            }
            set {
                this.aSerConsultadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool modelado {
            get {
                return this.modeladoField;
            }
            set {
                this.modeladoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modeladoSpecified {
            get {
                return this.modeladoFieldSpecified;
            }
            set {
                this.modeladoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool completamenteDefinido {
            get {
                return this.completamenteDefinidoField;
            }
            set {
                this.completamenteDefinidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool completamenteDefinidoSpecified {
            get {
                return this.completamenteDefinidoFieldSpecified;
            }
            set {
                this.completamenteDefinidoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool publicado {
            get {
                return this.publicadoField;
            }
            set {
                this.publicadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publicadoSpecified {
            get {
                return this.publicadoFieldSpecified;
            }
            set {
                this.publicadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool valido {
            get {
                return this.validoField;
            }
            set {
                this.validoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validoSpecified {
            get {
                return this.validoFieldSpecified;
            }
            set {
                this.validoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime validoHasta {
            get {
                return this.validoHastaField;
            }
            set {
                this.validoHastaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validoHastaSpecified {
            get {
                return this.validoHastaFieldSpecified;
            }
            set {
                this.validoHastaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
            }
        }
        
        /// <remarks/>
        public Categoria categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("refSet", IsNullable=false)]
        public RefSet[] refSets {
            get {
                return this.refSetsField;
            }
            set {
                this.refSetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("descripcion", IsNullable=false)]
        public Descripcion[] descripciones {
            get {
                return this.descripcionesField;
            }
            set {
                this.descripcionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("atributo", IsNullable=false)]
        public Atributo[] atributos {
            get {
                return this.atributosField;
            }
            set {
                this.atributosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("relacion", IsNullable=false)]
        public Relacion[] relaciones {
            get {
                return this.relacionesField;
            }
            set {
                this.relacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("relacionSnomedCT", IsNullable=false)]
        public RelacionSnomedCT[] relacionesSnomedCT {
            get {
                return this.relacionesSnomedCTField;
            }
            set {
                this.relacionesSnomedCTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("crossmapIndirecto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public IndirectCrossmap[] crossmapsIndirectos {
            get {
                return this.crossmapsIndirectosField;
            }
            set {
                this.crossmapsIndirectosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("crossmapDirecto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CrossmapSetMember[] crossmapsDirectos {
            get {
                return this.crossmapsDirectosField;
            }
            set {
                this.crossmapsDirectosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class Categoria {
        
        private string nombreField;
        
        private string nombreAbreviadoField;
        
        private bool restringidaField;
        
        private bool restringidaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreAbreviado {
            get {
                return this.nombreAbreviadoField;
            }
            set {
                this.nombreAbreviadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool restringida {
            get {
                return this.restringidaField;
            }
            set {
                this.restringidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool restringidaSpecified {
            get {
                return this.restringidaFieldSpecified;
            }
            set {
                this.restringidaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class RefSet {
        
        private string nombreField;
        
        private bool validoField;
        
        private bool validoFieldSpecified;
        
        private System.DateTime validoHastaField;
        
        private bool validoHastaFieldSpecified;
        
        private System.DateTime creadoEnField;
        
        private bool creadoEnFieldSpecified;
        
        private string institucionField;
        
        private Concepto[] conceptosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool valido {
            get {
                return this.validoField;
            }
            set {
                this.validoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validoSpecified {
            get {
                return this.validoFieldSpecified;
            }
            set {
                this.validoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime validoHasta {
            get {
                return this.validoHastaField;
            }
            set {
                this.validoHastaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validoHastaSpecified {
            get {
                return this.validoHastaFieldSpecified;
            }
            set {
                this.validoHastaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime creadoEn {
            get {
                return this.creadoEnField;
            }
            set {
                this.creadoEnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creadoEnSpecified {
            get {
                return this.creadoEnFieldSpecified;
            }
            set {
                this.creadoEnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string institucion {
            get {
                return this.institucionField;
            }
            set {
                this.institucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("concepto", IsNullable=false)]
        public Concepto[] conceptos {
            get {
                return this.conceptosField;
            }
            set {
                this.conceptosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class Descripcion {
        
        private string idField;
        
        private string tipoField;
        
        private string terminoField;
        
        private bool validaField;
        
        private bool validaFieldSpecified;
        
        private bool esSensibleAMayusculasField;
        
        private bool esSensibleAMayusculasFieldSpecified;
        
        private bool nombreAutgeneradoField;
        
        private bool nombreAutgeneradoFieldSpecified;
        
        private bool publicadoField;
        
        private bool publicadoFieldSpecified;
        
        private bool modeladoField;
        
        private bool modeladoFieldSpecified;
        
        private System.DateTime validaHastaField;
        
        private bool validaHastaFieldSpecified;
        
        private System.DateTime creadoField;
        
        private bool creadoFieldSpecified;
        
        private long usosField;
        
        private bool usosFieldSpecified;
        
        private Usuario usuarioCreadorField;
        
        private Concepto conceptoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string termino {
            get {
                return this.terminoField;
            }
            set {
                this.terminoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool valida {
            get {
                return this.validaField;
            }
            set {
                this.validaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validaSpecified {
            get {
                return this.validaFieldSpecified;
            }
            set {
                this.validaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool esSensibleAMayusculas {
            get {
                return this.esSensibleAMayusculasField;
            }
            set {
                this.esSensibleAMayusculasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool esSensibleAMayusculasSpecified {
            get {
                return this.esSensibleAMayusculasFieldSpecified;
            }
            set {
                this.esSensibleAMayusculasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool nombreAutgenerado {
            get {
                return this.nombreAutgeneradoField;
            }
            set {
                this.nombreAutgeneradoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nombreAutgeneradoSpecified {
            get {
                return this.nombreAutgeneradoFieldSpecified;
            }
            set {
                this.nombreAutgeneradoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool publicado {
            get {
                return this.publicadoField;
            }
            set {
                this.publicadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publicadoSpecified {
            get {
                return this.publicadoFieldSpecified;
            }
            set {
                this.publicadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool modelado {
            get {
                return this.modeladoField;
            }
            set {
                this.modeladoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modeladoSpecified {
            get {
                return this.modeladoFieldSpecified;
            }
            set {
                this.modeladoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime validaHasta {
            get {
                return this.validaHastaField;
            }
            set {
                this.validaHastaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validaHastaSpecified {
            get {
                return this.validaHastaFieldSpecified;
            }
            set {
                this.validaHastaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime creado {
            get {
                return this.creadoField;
            }
            set {
                this.creadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creadoSpecified {
            get {
                return this.creadoFieldSpecified;
            }
            set {
                this.creadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long usos {
            get {
                return this.usosField;
            }
            set {
                this.usosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usosSpecified {
            get {
                return this.usosFieldSpecified;
            }
            set {
                this.usosFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Usuario usuarioCreador {
            get {
                return this.usuarioCreadorField;
            }
            set {
                this.usuarioCreadorField = value;
            }
        }
        
        /// <remarks/>
        public Concepto concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class Usuario {
        
        private string nombreUsuarioField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string segundoApellidoField;
        
        private string emailField;
        
        private string rutField;
        
        private System.DateTime ultimoLoginField;
        
        private bool ultimoLoginFieldSpecified;
        
        private System.DateTime ultimoCambioPasswordField;
        
        private bool ultimoCambioPasswordFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime ultimoLogin {
            get {
                return this.ultimoLoginField;
            }
            set {
                this.ultimoLoginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ultimoLoginSpecified {
            get {
                return this.ultimoLoginFieldSpecified;
            }
            set {
                this.ultimoLoginFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime ultimoCambioPassword {
            get {
                return this.ultimoCambioPasswordField;
            }
            set {
                this.ultimoCambioPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ultimoCambioPasswordSpecified {
            get {
                return this.ultimoCambioPasswordFieldSpecified;
            }
            set {
                this.ultimoCambioPasswordFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class Atributo {
        
        private string tipoField;
        
        private string nombreField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class Relacion {
        
        private Objetivo objetivoField;
        
        private DefinicionRelacion definicionField;
        
        private Concepto conceptoField;
        
        private AtributoRelacion[] atributosField;
        
        /// <remarks/>
        public Objetivo objetivo {
            get {
                return this.objetivoField;
            }
            set {
                this.objetivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DefinicionRelacion definicion {
            get {
                return this.definicionField;
            }
            set {
                this.definicionField = value;
            }
        }
        
        /// <remarks/>
        public Concepto concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("atributo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AtributoRelacion[] atributos {
            get {
                return this.atributosField;
            }
            set {
                this.atributosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class DefinicionRelacion {
        
        private string nameField;
        
        private string descriptionField;
        
        private Multiplicidad multiplicidadField;
        
        private DefinicionObjetivo definicionObjetivoField;
        
        private DefinicionRelacion definicionRelacionExcluidaField;
        
        private DefinicionRelacionAtributo[] definicionesAtributoRelacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Multiplicidad multiplicidad {
            get {
                return this.multiplicidadField;
            }
            set {
                this.multiplicidadField = value;
            }
        }
        
        /// <remarks/>
        public DefinicionObjetivo definicionObjetivo {
            get {
                return this.definicionObjetivoField;
            }
            set {
                this.definicionObjetivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DefinicionRelacion definicionRelacionExcluida {
            get {
                return this.definicionRelacionExcluidaField;
            }
            set {
                this.definicionRelacionExcluidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("definicionAtributoRelacion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DefinicionRelacionAtributo[] definicionesAtributoRelacion {
            get {
                return this.definicionesAtributoRelacionField;
            }
            set {
                this.definicionesAtributoRelacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class Multiplicidad {
        
        private int limiteInferiorField;
        
        private bool limiteInferiorFieldSpecified;
        
        private int limiteSuperiorField;
        
        private bool limiteSuperiorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int limiteInferior {
            get {
                return this.limiteInferiorField;
            }
            set {
                this.limiteInferiorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool limiteInferiorSpecified {
            get {
                return this.limiteInferiorFieldSpecified;
            }
            set {
                this.limiteInferiorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int limiteSuperior {
            get {
                return this.limiteSuperiorField;
            }
            set {
                this.limiteSuperiorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool limiteSuperiorSpecified {
            get {
                return this.limiteSuperiorFieldSpecified;
            }
            set {
                this.limiteSuperiorFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class DefinicionObjetivo {
        
        private bool esTipoBasicoField;
        
        private bool esTipoBasicoFieldSpecified;
        
        private bool esTipoSMTKField;
        
        private bool esTipoSMTKFieldSpecified;
        
        private bool esTablaAuxiliarField;
        
        private bool esTablaAuxiliarFieldSpecified;
        
        private bool esTipoSnomedCTField;
        
        private bool esTipoSnomedCTFieldSpecified;
        
        private bool esTipoCrossMapField;
        
        private bool esTipoCrossMapFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool esTipoBasico {
            get {
                return this.esTipoBasicoField;
            }
            set {
                this.esTipoBasicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool esTipoBasicoSpecified {
            get {
                return this.esTipoBasicoFieldSpecified;
            }
            set {
                this.esTipoBasicoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool esTipoSMTK {
            get {
                return this.esTipoSMTKField;
            }
            set {
                this.esTipoSMTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool esTipoSMTKSpecified {
            get {
                return this.esTipoSMTKFieldSpecified;
            }
            set {
                this.esTipoSMTKFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool esTablaAuxiliar {
            get {
                return this.esTablaAuxiliarField;
            }
            set {
                this.esTablaAuxiliarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool esTablaAuxiliarSpecified {
            get {
                return this.esTablaAuxiliarFieldSpecified;
            }
            set {
                this.esTablaAuxiliarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool esTipoSnomedCT {
            get {
                return this.esTipoSnomedCTField;
            }
            set {
                this.esTipoSnomedCTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool esTipoSnomedCTSpecified {
            get {
                return this.esTipoSnomedCTFieldSpecified;
            }
            set {
                this.esTipoSnomedCTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool esTipoCrossMap {
            get {
                return this.esTipoCrossMapField;
            }
            set {
                this.esTipoCrossMapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool esTipoCrossMapSpecified {
            get {
                return this.esTipoCrossMapFieldSpecified;
            }
            set {
                this.esTipoCrossMapFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class DefinicionRelacionAtributo {
        
        private string nameField;
        
        private Multiplicidad multiplicidadField;
        
        private DefinicionObjetivo definicionObjetivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Multiplicidad multiplicidad {
            get {
                return this.multiplicidadField;
            }
            set {
                this.multiplicidadField = value;
            }
        }
        
        /// <remarks/>
        public DefinicionObjetivo definicionObjetivo {
            get {
                return this.definicionObjetivoField;
            }
            set {
                this.definicionObjetivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class TablaAuxiliar {
        
        private string nombreField;
        
        private string descripcionField;
        
        private string nombreTablaField;
        
        private ColumnaTablaAuxiliar[] columnaTablaAuxiliarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreTabla {
            get {
                return this.nombreTablaField;
            }
            set {
                this.nombreTablaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("columna", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ColumnaTablaAuxiliar[] columnaTablaAuxiliar {
            get {
                return this.columnaTablaAuxiliarField;
            }
            set {
                this.columnaTablaAuxiliarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class ColumnaTablaAuxiliar {
        
        private string nombreColumnaField;
        
        private bool esBuscableField;
        
        private bool esBuscableFieldSpecified;
        
        private bool esMostrableField;
        
        private bool esMostrableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreColumna {
            get {
                return this.nombreColumnaField;
            }
            set {
                this.nombreColumnaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool esBuscable {
            get {
                return this.esBuscableField;
            }
            set {
                this.esBuscableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool esBuscableSpecified {
            get {
                return this.esBuscableFieldSpecified;
            }
            set {
                this.esBuscableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool esMostrable {
            get {
                return this.esMostrableField;
            }
            set {
                this.esMostrableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool esMostrableSpecified {
            get {
                return this.esMostrableFieldSpecified;
            }
            set {
                this.esMostrableFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class ObjetivoEntry {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ws.semantikos.minsal.cl/")]
    public partial class RespuestaCodificacionDeNuevoTermino {
        
        private string id_descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id_descripcion {
            get {
                return this.id_descripcionField;
            }
            set {
                this.id_descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36366")]
    public delegate void codificacionDeNuevoTerminoCompletedEventHandler(object sender, codificacionDeNuevoTerminoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36366")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class codificacionDeNuevoTerminoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal codificacionDeNuevoTerminoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaCodificacionDeNuevoTermino Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaCodificacionDeNuevoTermino)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36366")]
    public delegate void incrementarContadorDescripcionConsumidaCompletedEventHandler(object sender, incrementarContadorDescripcionConsumidaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36366")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class incrementarContadorDescripcionConsumidaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal incrementarContadorDescripcionConsumidaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Descripcion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Descripcion)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591