    package cl.minsal.semantikos.model.dtos;

import cl.minsal.semantikos.model.ConceptSMTK;
import cl.minsal.semantikos.model.DAO;
import cl.minsal.semantikos.model.PersistentEntity;
import cl.minsal.semantikos.model.audit.AuditableEntity;
import cl.minsal.semantikos.model.descriptions.DescriptionType;
import cl.minsal.semantikos.model.tags.TagSMTKFactory;
import cl.minsal.semantikos.model.users.User;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static java.lang.System.currentTimeMillis;

    /**
     * @author Andrés Farías on 08-07-16.
     */
    public class DescriptionDTO extends PersistentEntity implements Serializable {

        /** El término que representa esta descripción */
        private String term;

        /** El DESCRIPTION_ID (valor de negocio) de la descripción */
        private String descriptionID;

        private boolean caseSensitive;

        private boolean autogeneratedName;

        private boolean published;

        /** El tipo de descriptor */
        private long idDescriptionType;

        /** El estado del descriptor */
        private boolean modeled;

        /** La descripción es Vigente (válida) hasta la fecha... */
        private Timestamp validityUntil;

        /** La fecha de creación */
        private Timestamp creationDate;

        /** Usuario que creo la descripción */
        private long idUser;

        /** Cantidad de usos de la descripción */
        private long uses;

        /** El concepto al cuál está asociada la descripción */
        private ConceptDTO conceptDTO;

        public DescriptionDTO() {
        }

        public String getDescriptionID() {
            return descriptionID;
        }

        public void setDescriptionID(String descriptionID) {
            this.descriptionID = descriptionID;
        }

        public long getIdDescriptionType() {
            return idDescriptionType;
        }

        public void setIdDescriptionType(long idDescriptionTypeId) {
            this.idDescriptionType = idDescriptionTypeId;
        }

        public String getDescriptionId() {
            return descriptionID;
        }

        public void setDescriptionId(String idDescription) {
            this.descriptionID = idDescription;
        }

        public String getTerm() {
            return term;
        }

        public void setTerm(String term) {
            this.term = term;
        }

        public boolean isAutogeneratedName() {
            return autogeneratedName;
        }

        public void setAutogeneratedName(boolean autogeneratedName) {
            this.autogeneratedName = autogeneratedName;
        }

        public boolean isCaseSensitive() {
            return caseSensitive;
        }

        public void setCaseSensitive(boolean caseSensitive) {
            this.caseSensitive = caseSensitive;
        }

        public boolean isPublished() {
            return published;
        }

        public void setPublished(boolean published) {
            this.published = published;
        }

        public Timestamp getValidityUntil() {
            return validityUntil;
        }

        public void setValidityUntil(Timestamp validityUntil) {
            this.validityUntil = validityUntil;
        }

        public long getUses() {
            return uses;
        }

        public void setUses(long uses) {
            this.uses = uses;
        }

        public boolean isModeled() {
            return modeled;
        }

        public void setModeled(boolean modeled) {
            this.modeled = modeled;
        }

        public boolean isValid() {
            return (getValidityUntil() == null || getValidityUntil().after(new Timestamp(currentTimeMillis())));
        }

        public ConceptDTO getConceptDTO() {
            return conceptDTO;
        }

        public void setConceptDTO(ConceptDTO conceptDTO) {
            this.conceptDTO = conceptDTO;
        }

        public long getIdUser() {
            return idUser;
        }

        public void setIdUser(long idUser) {
            this.idUser = idUser;
        }

        public Timestamp getCreationDate() {
            return creationDate;
        }

        public void setCreationDate(Timestamp creationDate) {
            this.creationDate = creationDate;
        }

        @Override
        public String toString() {
            return this.term;
        }

    }
