package cl.minsal.semantikos.ws.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import java.io.Serializable;
import java.util.Date;

/**
 * Created by Development on 2016-10-13.
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "descripcion")
public class DescriptionResponse implements Serializable, Comparable<DescriptionResponse> {

    @XmlElement(name="id")
    private String descriptionID;
    @XmlElement(name="tipo")
    private String type;
    @XmlElement(name="termino")
    private String term;
    @XmlElement(name="valida")
    private Boolean isValid;
    @XmlElement(name="esSensibleAMayusculas")
    private Boolean isCaseSensitive;
    @XmlElement(name="nombreAutgenerado")
    private Boolean autogeneratedName;
    @XmlElement(name="publicado")
    private Boolean isPublished;
    @XmlElement(name="modelado")
    private Boolean modeled;
    @XmlElement(name="validaHasta")
    private Date validityUntil;
    @XmlElement(name="creado")
    private Date creationDate;
    @XmlElement(name="usos")
    private Long uses;
    @XmlElement(name="usuarioCreador")
    private UserResponse creatorUser;
    @XmlElement(name="concepto")
    private ConceptResponse conceptSMTK;

    public String getDescriptionID() {
        return descriptionID;
    }

    public void setDescriptionID(String descriptionID) {
        this.descriptionID = descriptionID;
    }

    public String getTerm() {
        return term;
    }

    public void setTerm(String term) {
        this.term = term;
    }

    public Boolean getCaseSensitive() {
        return isCaseSensitive;
    }

    public void setCaseSensitive(Boolean caseSensitive) {
        isCaseSensitive = caseSensitive;
    }

    public Boolean getAutogeneratedName() {
        return autogeneratedName;
    }

    public void setAutogeneratedName(Boolean autogeneratedName) {
        this.autogeneratedName = autogeneratedName;
    }

    public Boolean getPublished() {
        return isPublished;
    }

    public void setPublished(Boolean published) {
        isPublished = published;
    }

    public Boolean getModeled() {
        return modeled;
    }

    public void setModeled(Boolean modeled) {
        this.modeled = modeled;
    }

    public Date getValidityUntil() {
        return validityUntil;
    }

    public void setValidityUntil(Date validityUntil) {
        this.validityUntil = validityUntil;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public Long getUses() {
        return uses;
    }

    public void setUses(Long uses) {
        this.uses = uses;
    }

    public UserResponse getCreatorUser() {
        return creatorUser;
    }

    public void setCreatorUser(UserResponse creatorUser) {
        this.creatorUser = creatorUser;
    }

    public ConceptResponse getConceptSMTK() {
        return conceptSMTK;
    }

    public void setConceptSMTK(ConceptResponse conceptSMTK) {
        this.conceptSMTK = conceptSMTK;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Boolean getValid() {
        return isValid;
    }

    public void setValid(Boolean valid) {
        isValid = valid;
    }

    @Override
    public int compareTo(DescriptionResponse o) {
        if ( this.getType() != null ) {
            if ( "preferida".equalsIgnoreCase(this.getType()) ) {
                return -1;
            } else if ( "FSN".equalsIgnoreCase(this.getType()) ) {
                if ( "preferida".equalsIgnoreCase(o.getType()) ) {
                    return 1;
                } else {
                    return -1;
                }
            }
        }
        return 0;
    }
}
